-- Schema kiểm thử H2, giữ tên cột và ràng buộc tương ứng SQL Server.
DROP ALL OBJECTS;
CREATE SCHEMA dbo;
CREATE TABLE dbo.[ROLE] (
        RoleID INT IDENTITY(1,1) CONSTRAINT PK_ROLE PRIMARY KEY,
        RoleName NVARCHAR(50) NOT NULL CONSTRAINT UQ_ROLE_Name UNIQUE
    );
CREATE TABLE dbo.[PERMISSION] (
        PermissionID INT IDENTITY(1,1) CONSTRAINT PK_PERMISSION PRIMARY KEY,
        PermissionName NVARCHAR(100) NOT NULL CONSTRAINT UQ_PERMISSION_Name UNIQUE
    );
CREATE TABLE dbo.[USER] (
        UserID INT IDENTITY(1,1) CONSTRAINT PK_USER PRIMARY KEY,
        FullName NVARCHAR(100) NOT NULL,
        Email VARCHAR(254) NOT NULL CONSTRAINT UQ_USER_Email UNIQUE,
        -- Lưu mã băm mật khẩu do ứng dụng tạo; không lưu mật khẩu dạng văn bản thuần.
        [Password] VARCHAR(255) NOT NULL,
        RoleID INT NOT NULL,
        CONSTRAINT FK_USER_ROLE FOREIGN KEY (RoleID) REFERENCES dbo.[ROLE](RoleID)
    );
CREATE TABLE dbo.ROLEPERMISSION (
        RoleID INT NOT NULL,
        PermissionID INT NOT NULL,
        CONSTRAINT PK_ROLEPERMISSION PRIMARY KEY (RoleID, PermissionID),
        CONSTRAINT FK_ROLEPERMISSION_ROLE FOREIGN KEY (RoleID) REFERENCES dbo.[ROLE](RoleID),
        CONSTRAINT FK_ROLEPERMISSION_PERMISSION FOREIGN KEY (PermissionID) REFERENCES dbo.[PERMISSION](PermissionID)
    );
CREATE TABLE dbo.Horse (
        HorseID INT IDENTITY(1,1) CONSTRAINT PK_Horse PRIMARY KEY,
        [Name] NVARCHAR(100) NOT NULL,
        Gender NVARCHAR(20) NOT NULL,
        Age INT NOT NULL,
        [Weight] DECIMAL(7,2) NOT NULL,
        Lineage NVARCHAR(255) NULL,
        OwnerID INT NOT NULL,
        CONSTRAINT CK_Horse_Age CHECK (Age >= 0),
        CONSTRAINT CK_Horse_Weight CHECK ([Weight] > 0),
        CONSTRAINT FK_Horse_Owner FOREIGN KEY (OwnerID) REFERENCES dbo.[USER](UserID)
    );
CREATE TABLE dbo.TRAININGPLAN (
        PlanID INT IDENTITY(1,1) CONSTRAINT PK_TRAININGPLAN PRIMARY KEY,
        HorseID INT NOT NULL,
        Distance DECIMAL(10,2) NOT NULL,
        Workload DECIMAL(10,2) NOT NULL,
        Phase NVARCHAR(50) NOT NULL,
        CreatedBy INT NOT NULL,
        CONSTRAINT CK_TRAININGPLAN_Distance CHECK (Distance >= 0),
        CONSTRAINT CK_TRAININGPLAN_Workload CHECK (Workload >= 0),
        CONSTRAINT FK_TRAININGPLAN_Horse FOREIGN KEY (HorseID) REFERENCES dbo.Horse(HorseID),
        CONSTRAINT FK_TRAININGPLAN_Creator FOREIGN KEY (CreatedBy) REFERENCES dbo.[USER](UserID)
    );
CREATE TABLE dbo.TRAININGSCHEDULE (
        ScheduleID INT IDENTITY(1,1) CONSTRAINT PK_TRAININGSCHEDULE PRIMARY KEY,
        HorseID INT NOT NULL,
        GroomID INT NOT NULL,
        [Date] DATE NOT NULL,
        [Time] TIME(0) NOT NULL,
        CONSTRAINT FK_TRAININGSCHEDULE_Horse FOREIGN KEY (HorseID) REFERENCES dbo.Horse(HorseID),
        CONSTRAINT FK_TRAININGSCHEDULE_Groom FOREIGN KEY (GroomID) REFERENCES dbo.[USER](UserID)
    );
CREATE TABLE dbo.TRAININGSESSION (
        SessionID INT IDENTITY(1,1) CONSTRAINT PK_TRAININGSESSION PRIMARY KEY,
        HorseID INT NOT NULL,
        HeartRate INT NOT NULL,
        Speed DECIMAL(7,2) NOT NULL,
        TrainingIndex NVARCHAR(50) NOT NULL,
        [Comment] NVARCHAR(MAX) NULL,
        [Date] DATE NOT NULL,
        CONSTRAINT CK_TRAININGSESSION_HeartRate CHECK (HeartRate > 0),
        CONSTRAINT CK_TRAININGSESSION_Speed CHECK (Speed >= 0),
        CONSTRAINT FK_TRAININGSESSION_Horse FOREIGN KEY (HorseID) REFERENCES dbo.Horse(HorseID)
    );
CREATE TABLE dbo.STABLEASSIGNMENT (
        StableID INT IDENTITY(1,1) CONSTRAINT PK_STABLEASSIGNMENT PRIMARY KEY,
        HorseID INT NOT NULL,
        StallNumber NVARCHAR(20) NOT NULL,
        DailyRoutine NVARCHAR(MAX) NULL,
        CONSTRAINT FK_STABLEASSIGNMENT_Horse FOREIGN KEY (HorseID) REFERENCES dbo.Horse(HorseID)
    );
CREATE TABLE dbo.RACE (
        RaceID INT IDENTITY(1,1) CONSTRAINT PK_RACE PRIMARY KEY,
        RaceName NVARCHAR(150) NOT NULL,
        [Date] DATE NOT NULL,
        [Time] TIME(0) NOT NULL
    );
CREATE TABLE dbo.RACEREGISTRATION (
        HorseID INT NOT NULL,
        RaceID INT NOT NULL,
        RegistrationDate DATE NOT NULL,
        CONSTRAINT PK_RACEREGISTRATION PRIMARY KEY (HorseID, RaceID),
        CONSTRAINT FK_RACEREGISTRATION_Horse FOREIGN KEY (HorseID) REFERENCES dbo.Horse(HorseID),
        CONSTRAINT FK_RACEREGISTRATION_Race FOREIGN KEY (RaceID) REFERENCES dbo.RACE(RaceID)
    );
CREATE TABLE dbo.MEDICALRECORD (
        RecordID INT IDENTITY(1,1) CONSTRAINT PK_MEDICALRECORD PRIMARY KEY,
        HorseID INT NOT NULL,
        VetID INT NOT NULL,
        Diagnosis NVARCHAR(MAX) NOT NULL,
        Treatment NVARCHAR(MAX) NULL,
        InjuryLocation NVARCHAR(100) NULL,
        [Date] DATE NOT NULL,
        CONSTRAINT FK_MEDICALRECORD_Horse FOREIGN KEY (HorseID) REFERENCES dbo.Horse(HorseID),
        CONSTRAINT FK_MEDICALRECORD_Vet FOREIGN KEY (VetID) REFERENCES dbo.[USER](UserID)
    );
CREATE TABLE dbo.TRAININGLOCK (
        LockID INT IDENTITY(1,1) CONSTRAINT PK_TRAININGLOCK PRIMARY KEY,
        HorseID INT NOT NULL,
        VetID INT NOT NULL,
        Reason NVARCHAR(MAX) NOT NULL,
        StartDate DATE NOT NULL,
        EndDate DATE NULL,
        CONSTRAINT CK_TRAININGLOCK_Dates CHECK (EndDate IS NULL OR EndDate >= StartDate),
        CONSTRAINT FK_TRAININGLOCK_Horse FOREIGN KEY (HorseID) REFERENCES dbo.Horse(HorseID),
        CONSTRAINT FK_TRAININGLOCK_Vet FOREIGN KEY (VetID) REFERENCES dbo.[USER](UserID)
    );
CREATE TABLE dbo.CARETASK (
        TaskID INT IDENTITY(1,1) CONSTRAINT PK_CARETASK PRIMARY KEY,
        HorseID INT NOT NULL,
        GroomID INT NOT NULL,
        TaskType NVARCHAR(100) NOT NULL,
        [Status] BIT NOT NULL DEFAULT (0),
        [Date] DATE NOT NULL,
        CONSTRAINT FK_CARETASK_Horse FOREIGN KEY (HorseID) REFERENCES dbo.Horse(HorseID),
        CONSTRAINT FK_CARETASK_Groom FOREIGN KEY (GroomID) REFERENCES dbo.[USER](UserID)
    );
CREATE TABLE dbo.HEALTHSTATUS (
        HorseID INT CONSTRAINT PK_HEALTHSTATUS PRIMARY KEY,
        [Status] NVARCHAR(50) NOT NULL,
        LastUpdate DATE NOT NULL,
        CONSTRAINT FK_HEALTHSTATUS_Horse FOREIGN KEY (HorseID) REFERENCES dbo.Horse(HorseID)
    );
CREATE TABLE dbo.VACCINATIONSCHEDULE (
        ScheduleID INT IDENTITY(1,1) CONSTRAINT PK_VACCINATIONSCHEDULE PRIMARY KEY,
        HorseID INT NOT NULL,
        [Type] NVARCHAR(100) NOT NULL,
        ScheduleDate DATE NOT NULL,
        [Status] NVARCHAR(50) NOT NULL,
        CONSTRAINT FK_VACCINATIONSCHEDULE_Horse FOREIGN KEY (HorseID) REFERENCES dbo.Horse(HorseID)
    );
CREATE TABLE dbo.FEEDINGPLAN (
        FeedID INT IDENTITY(1,1) CONSTRAINT PK_FEEDINGPLAN PRIMARY KEY,
        HorseID INT NOT NULL,
        Grain DECIMAL(8,3) NOT NULL,
        Grass DECIMAL(8,3) NOT NULL,
        Vitamin DECIMAL(8,3) NOT NULL,
        Meal NVARCHAR(50) NOT NULL,
        CONSTRAINT CK_FEEDINGPLAN_Amounts CHECK (Grain >= 0 AND Grass >= 0 AND Vitamin >= 0),
        CONSTRAINT FK_FEEDINGPLAN_Horse FOREIGN KEY (HorseID) REFERENCES dbo.Horse(HorseID)
    );
CREATE TABLE dbo.Supply (
        SupplyID INT IDENTITY(1,1) CONSTRAINT PK_Supply PRIMARY KEY,
        ItemName NVARCHAR(150) NOT NULL,
        [Type] NVARCHAR(50) NOT NULL,
        QuantityInStock INT NOT NULL DEFAULT (0),
        ManagedBy INT NOT NULL,
        CONSTRAINT CK_Supply_Quantity CHECK (QuantityInStock >= 0),
        CONSTRAINT FK_Supply_Manager FOREIGN KEY (ManagedBy) REFERENCES dbo.[USER](UserID)
    );
CREATE TABLE dbo.AuditLog (
        LogID INT IDENTITY(1,1) CONSTRAINT PK_AuditLog PRIMARY KEY,
        UserID INT NOT NULL,
        [Action] NVARCHAR(100) NOT NULL,
        TargetTable NVARCHAR(128) NOT NULL,
        TargetID INT NOT NULL,
        [TimeStamp] DATETIME2(0) NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT FK_AuditLog_User FOREIGN KEY (UserID) REFERENCES dbo.[USER](UserID)
    );
CREATE TABLE dbo.INCIDENTREPORT (
        ReportID INT IDENTITY(1,1) CONSTRAINT PK_INCIDENTREPORT PRIMARY KEY,
        HorseID INT NOT NULL,
        GroomID INT NOT NULL,
        IncidentType NVARCHAR(100) NOT NULL,
        ImagePath NVARCHAR(500) NULL,
        [Date] DATE NOT NULL,
        CONSTRAINT FK_INCIDENTREPORT_Horse FOREIGN KEY (HorseID) REFERENCES dbo.Horse(HorseID),
        CONSTRAINT FK_INCIDENTREPORT_Groom FOREIGN KEY (GroomID) REFERENCES dbo.[USER](UserID)
    );
ALTER TABLE dbo.[USER] ADD AccountStatus VARCHAR(16) NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE dbo.[USER] ADD CONSTRAINT CK_USER_AccountStatus CHECK (AccountStatus IN ('PENDING','ACTIVE','DISABLED','REJECTED'));
ALTER TABLE dbo.Horse ADD Archived BIT NOT NULL DEFAULT 0;
ALTER TABLE dbo.Supply ADD Archived BIT NOT NULL DEFAULT 0;
ALTER TABLE dbo.Supply ADD [Version] INT NOT NULL DEFAULT 0;
ALTER TABLE dbo.INCIDENTREPORT ADD [Description] NVARCHAR(2000);
CREATE TABLE dbo.ApiToken (
            TokenHash CHAR(64) CONSTRAINT PK_ApiToken PRIMARY KEY,
            UserID INT NOT NULL CONSTRAINT FK_ApiToken_User REFERENCES dbo.[USER](UserID),
            ExpiresAt DATETIME2(3) NOT NULL
        );
CREATE TABLE dbo.FinanceEntry (
            EntryID INT IDENTITY(1,1) CONSTRAINT PK_FinanceEntry PRIMARY KEY,
            HorseID INT NULL CONSTRAINT FK_FinanceEntry_Horse REFERENCES dbo.Horse(HorseID),
            EntryType VARCHAR(10) NOT NULL CONSTRAINT CK_FinanceEntry_Type CHECK (EntryType IN ('INCOME','EXPENSE')),
            Amount DECIMAL(18,2) NOT NULL CONSTRAINT CK_FinanceEntry_Amount CHECK (Amount>0),
            Category NVARCHAR(100) NOT NULL,
            [Description] NVARCHAR(1000) NULL,
            EntryDate DATE NOT NULL,
            CreatedBy INT NOT NULL CONSTRAINT FK_FinanceEntry_User REFERENCES dbo.[USER](UserID)
        );