USE [HorseManagement];
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO
-- Chỉ tạo cấu trúc lần đầu; dừng nếu đã có bảng để bảo vệ dữ liệu hiện tại.
IF EXISTS (SELECT 1 FROM sys.tables WHERE schema_id = SCHEMA_ID(N'dbo'))
    THROW 50001, 'Database already contains dbo tables. Schema was not changed.', 1;

BEGIN TRY
    BEGIN TRANSACTION;

    CREATE TABLE dbo.[ROLE] (
        RoleID INT IDENTITY(1,1) CONSTRAINT PK_ROLE PRIMARY KEY,
        RoleName NVARCHAR(50) NOT NULL CONSTRAINT UQ_ROLE_Name UNIQUE
    );

    CREATE TABLE dbo.[PERMISSION] (
        PermissionID INT IDENTITY(1,1) CONSTRAINT PK_PERMISSION PRIMARY KEY,
        PermissionName NVARCHAR(100) NOT NULL CONSTRAINT UQ_PERMISSION_Name UNIQUE
    );

    CREATE TABLE dbo.[USER] (
        UserID INT IDENTITY(1,1) CONSTRAINT PK_USER PRIMARY KEY,
        FullName NVARCHAR(100) NOT NULL,
        Email VARCHAR(254) NOT NULL CONSTRAINT UQ_USER_Email UNIQUE,
        -- Lưu mã băm mật khẩu do ứng dụng tạo; không lưu mật khẩu dạng văn bản thuần.
        [Password] VARCHAR(255) NOT NULL,
        RoleID INT NOT NULL,
        CONSTRAINT FK_USER_ROLE FOREIGN KEY (RoleID) REFERENCES dbo.[ROLE](RoleID)
    );

    CREATE TABLE dbo.ROLEPERMISSION (
        RoleID INT NOT NULL,
        PermissionID INT NOT NULL,
        CONSTRAINT PK_ROLEPERMISSION PRIMARY KEY (RoleID, PermissionID),
        CONSTRAINT FK_ROLEPERMISSION_ROLE FOREIGN KEY (RoleID) REFERENCES dbo.[ROLE](RoleID),
        CONSTRAINT FK_ROLEPERMISSION_PERMISSION FOREIGN KEY (PermissionID) REFERENCES dbo.[PERMISSION](PermissionID)
    );

    CREATE TABLE dbo.Horse (
        HorseID INT IDENTITY(1,1) CONSTRAINT PK_Horse PRIMARY KEY,
        [Name] NVARCHAR(100) NOT NULL,
        Gender NVARCHAR(20) NOT NULL,
        Age INT NOT NULL,
        [Weight] DECIMAL(7,2) NOT NULL,
        Lineage NVARCHAR(255) NULL,
        OwnerID INT NOT NULL,
        CONSTRAINT CK_Horse_Age CHECK (Age >= 0),
        CONSTRAINT CK_Horse_Weight CHECK ([Weight] > 0),
        CONSTRAINT FK_Horse_Owner FOREIGN KEY (OwnerID) REFERENCES dbo.[USER](UserID)
    );

    CREATE TABLE dbo.TRAININGPLAN (
        PlanID INT IDENTITY(1,1) CONSTRAINT PK_TRAININGPLAN PRIMARY KEY,
        HorseID INT NOT NULL,
        Distance DECIMAL(10,2) NOT NULL,
        Workload DECIMAL(10,2) NOT NULL,
        Phase NVARCHAR(50) NOT NULL,
        CreatedBy INT NOT NULL,
        CONSTRAINT CK_TRAININGPLAN_Distance CHECK (Distance >= 0),
        CONSTRAINT CK_TRAININGPLAN_Workload CHECK (Workload >= 0),
        CONSTRAINT FK_TRAININGPLAN_Horse FOREIGN KEY (HorseID) REFERENCES dbo.Horse(HorseID),
        CONSTRAINT FK_TRAININGPLAN_Creator FOREIGN KEY (CreatedBy) REFERENCES dbo.[USER](UserID)
    );

    CREATE TABLE dbo.TRAININGSCHEDULE (
        ScheduleID INT IDENTITY(1,1) CONSTRAINT PK_TRAININGSCHEDULE PRIMARY KEY,
        HorseID INT NOT NULL,
        GroomID INT NOT NULL,
        [Date] DATE NOT NULL,
        [Time] TIME(0) NOT NULL,
        CONSTRAINT FK_TRAININGSCHEDULE_Horse FOREIGN KEY (HorseID) REFERENCES dbo.Horse(HorseID),
        CONSTRAINT FK_TRAININGSCHEDULE_Groom FOREIGN KEY (GroomID) REFERENCES dbo.[USER](UserID)
    );

    CREATE TABLE dbo.TRAININGSESSION (
        SessionID INT IDENTITY(1,1) CONSTRAINT PK_TRAININGSESSION PRIMARY KEY,
        HorseID INT NOT NULL,
        HeartRate INT NOT NULL,
        Speed DECIMAL(7,2) NOT NULL,
        TrainingIndex NVARCHAR(50) NOT NULL,
        [Comment] NVARCHAR(MAX) NULL,
        [Date] DATE NOT NULL,
        CONSTRAINT CK_TRAININGSESSION_HeartRate CHECK (HeartRate > 0),
        CONSTRAINT CK_TRAININGSESSION_Speed CHECK (Speed >= 0),
        CONSTRAINT FK_TRAININGSESSION_Horse FOREIGN KEY (HorseID) REFERENCES dbo.Horse(HorseID)
    );

    CREATE TABLE dbo.STABLEASSIGNMENT (
        StableID INT IDENTITY(1,1) CONSTRAINT PK_STABLEASSIGNMENT PRIMARY KEY,
        HorseID INT NOT NULL,
        StallNumber NVARCHAR(20) NOT NULL,
        DailyRoutine NVARCHAR(MAX) NULL,
        CONSTRAINT FK_STABLEASSIGNMENT_Horse FOREIGN KEY (HorseID) REFERENCES dbo.Horse(HorseID)
    );

    CREATE TABLE dbo.RACE (
        RaceID INT IDENTITY(1,1) CONSTRAINT PK_RACE PRIMARY KEY,
        RaceName NVARCHAR(150) NOT NULL,
        [Date] DATE NOT NULL,
        [Time] TIME(0) NOT NULL
    );

    CREATE TABLE dbo.RACEREGISTRATION (
        HorseID INT NOT NULL,
        RaceID INT NOT NULL,
        RegistrationDate DATE NOT NULL,
        CONSTRAINT PK_RACEREGISTRATION PRIMARY KEY (HorseID, RaceID),
        CONSTRAINT FK_RACEREGISTRATION_Horse FOREIGN KEY (HorseID) REFERENCES dbo.Horse(HorseID),
        CONSTRAINT FK_RACEREGISTRATION_Race FOREIGN KEY (RaceID) REFERENCES dbo.RACE(RaceID)
    );

    CREATE TABLE dbo.MEDICALRECORD (
        RecordID INT IDENTITY(1,1) CONSTRAINT PK_MEDICALRECORD PRIMARY KEY,
        HorseID INT NOT NULL,
        VetID INT NOT NULL,
        Diagnosis NVARCHAR(MAX) NOT NULL,
        Treatment NVARCHAR(MAX) NULL,
        InjuryLocation NVARCHAR(100) NULL,
        [Date] DATE NOT NULL,
        CONSTRAINT FK_MEDICALRECORD_Horse FOREIGN KEY (HorseID) REFERENCES dbo.Horse(HorseID),
        CONSTRAINT FK_MEDICALRECORD_Vet FOREIGN KEY (VetID) REFERENCES dbo.[USER](UserID)
    );

    CREATE TABLE dbo.TRAININGLOCK (
        LockID INT IDENTITY(1,1) CONSTRAINT PK_TRAININGLOCK PRIMARY KEY,
        HorseID INT NOT NULL,
        VetID INT NOT NULL,
        Reason NVARCHAR(MAX) NOT NULL,
        StartDate DATE NOT NULL,
        EndDate DATE NULL,
        CONSTRAINT CK_TRAININGLOCK_Dates CHECK (EndDate IS NULL OR EndDate >= StartDate),
        CONSTRAINT FK_TRAININGLOCK_Horse FOREIGN KEY (HorseID) REFERENCES dbo.Horse(HorseID),
        CONSTRAINT FK_TRAININGLOCK_Vet FOREIGN KEY (VetID) REFERENCES dbo.[USER](UserID)
    );

    CREATE TABLE dbo.CARETASK (
        TaskID INT IDENTITY(1,1) CONSTRAINT PK_CARETASK PRIMARY KEY,
        HorseID INT NOT NULL,
        GroomID INT NOT NULL,
        TaskType NVARCHAR(100) NOT NULL,
        [Status] BIT NOT NULL CONSTRAINT DF_CARETASK_Status DEFAULT (0),
        [Date] DATE NOT NULL,
        CONSTRAINT FK_CARETASK_Horse FOREIGN KEY (HorseID) REFERENCES dbo.Horse(HorseID),
        CONSTRAINT FK_CARETASK_Groom FOREIGN KEY (GroomID) REFERENCES dbo.[USER](UserID)
    );

    CREATE TABLE dbo.HEALTHSTATUS (
        HorseID INT CONSTRAINT PK_HEALTHSTATUS PRIMARY KEY,
        [Status] NVARCHAR(50) NOT NULL,
        LastUpdate DATE NOT NULL,
        CONSTRAINT FK_HEALTHSTATUS_Horse FOREIGN KEY (HorseID) REFERENCES dbo.Horse(HorseID)
    );

    CREATE TABLE dbo.VACCINATIONSCHEDULE (
        ScheduleID INT IDENTITY(1,1) CONSTRAINT PK_VACCINATIONSCHEDULE PRIMARY KEY,
        HorseID INT NOT NULL,
        [Type] NVARCHAR(100) NOT NULL,
        ScheduleDate DATE NOT NULL,
        [Status] NVARCHAR(50) NOT NULL,
        CONSTRAINT FK_VACCINATIONSCHEDULE_Horse FOREIGN KEY (HorseID) REFERENCES dbo.Horse(HorseID)
    );

    CREATE TABLE dbo.FEEDINGPLAN (
        FeedID INT IDENTITY(1,1) CONSTRAINT PK_FEEDINGPLAN PRIMARY KEY,
        HorseID INT NOT NULL,
        Grain DECIMAL(8,3) NOT NULL,
        Grass DECIMAL(8,3) NOT NULL,
        Vitamin DECIMAL(8,3) NOT NULL,
        Meal NVARCHAR(50) NOT NULL,
        CONSTRAINT CK_FEEDINGPLAN_Amounts CHECK (Grain >= 0 AND Grass >= 0 AND Vitamin >= 0),
        CONSTRAINT FK_FEEDINGPLAN_Horse FOREIGN KEY (HorseID) REFERENCES dbo.Horse(HorseID)
    );

    CREATE TABLE dbo.Supply (
        SupplyID INT IDENTITY(1,1) CONSTRAINT PK_Supply PRIMARY KEY,
        ItemName NVARCHAR(150) NOT NULL,
        [Type] NVARCHAR(50) NOT NULL,
        QuantityInStock INT NOT NULL CONSTRAINT DF_Supply_Quantity DEFAULT (0),
        ManagedBy INT NOT NULL,
        CONSTRAINT CK_Supply_Quantity CHECK (QuantityInStock >= 0),
        CONSTRAINT FK_Supply_Manager FOREIGN KEY (ManagedBy) REFERENCES dbo.[USER](UserID)
    );

    CREATE TABLE dbo.AuditLog (
        LogID INT IDENTITY(1,1) CONSTRAINT PK_AuditLog PRIMARY KEY,
        UserID INT NOT NULL,
        [Action] NVARCHAR(100) NOT NULL,
        TargetTable NVARCHAR(128) NOT NULL,
        TargetID INT NOT NULL,
        [TimeStamp] DATETIME2(0) NOT NULL CONSTRAINT DF_AuditLog_TimeStamp DEFAULT (SYSDATETIME()),
        CONSTRAINT FK_AuditLog_User FOREIGN KEY (UserID) REFERENCES dbo.[USER](UserID)
    );

    CREATE TABLE dbo.INCIDENTREPORT (
        ReportID INT IDENTITY(1,1) CONSTRAINT PK_INCIDENTREPORT PRIMARY KEY,
        HorseID INT NOT NULL,
        GroomID INT NOT NULL,
        IncidentType NVARCHAR(100) NOT NULL,
        ImagePath NVARCHAR(500) NULL,
        [Date] DATE NOT NULL,
        CONSTRAINT FK_INCIDENTREPORT_Horse FOREIGN KEY (HorseID) REFERENCES dbo.Horse(HorseID),
        CONSTRAINT FK_INCIDENTREPORT_Groom FOREIGN KEY (GroomID) REFERENCES dbo.[USER](UserID)
    );

    -- Tạo chỉ mục cho các khóa ngoại chưa đứng đầu trong chỉ mục khóa chính.
    CREATE INDEX IX_USER_Role ON dbo.[USER](RoleID);
    CREATE INDEX IX_ROLEPERMISSION_Permission ON dbo.ROLEPERMISSION(PermissionID);
    CREATE INDEX IX_Horse_Owner ON dbo.Horse(OwnerID);
    CREATE INDEX IX_TRAININGPLAN_Horse ON dbo.TRAININGPLAN(HorseID);
    CREATE INDEX IX_TRAININGPLAN_Creator ON dbo.TRAININGPLAN(CreatedBy);
    CREATE INDEX IX_TRAININGSCHEDULE_HorseDate ON dbo.TRAININGSCHEDULE(HorseID, [Date], [Time]);
    CREATE INDEX IX_TRAININGSCHEDULE_GroomDate ON dbo.TRAININGSCHEDULE(GroomID, [Date], [Time]);
    CREATE INDEX IX_TRAININGSESSION_HorseDate ON dbo.TRAININGSESSION(HorseID, [Date]);
    CREATE INDEX IX_STABLEASSIGNMENT_Horse ON dbo.STABLEASSIGNMENT(HorseID);
    CREATE INDEX IX_RACEREGISTRATION_Race ON dbo.RACEREGISTRATION(RaceID);
    CREATE INDEX IX_MEDICALRECORD_HorseDate ON dbo.MEDICALRECORD(HorseID, [Date]);
    CREATE INDEX IX_MEDICALRECORD_Vet ON dbo.MEDICALRECORD(VetID);
    CREATE INDEX IX_TRAININGLOCK_HorseDates ON dbo.TRAININGLOCK(HorseID, StartDate, EndDate);
    CREATE INDEX IX_TRAININGLOCK_Vet ON dbo.TRAININGLOCK(VetID);
    CREATE INDEX IX_CARETASK_HorseDate ON dbo.CARETASK(HorseID, [Date]);
    CREATE INDEX IX_CARETASK_Groom ON dbo.CARETASK(GroomID);
    CREATE INDEX IX_VACCINATIONSCHEDULE_HorseDate ON dbo.VACCINATIONSCHEDULE(HorseID, ScheduleDate);
    CREATE INDEX IX_FEEDINGPLAN_Horse ON dbo.FEEDINGPLAN(HorseID);
    CREATE INDEX IX_Supply_Manager ON dbo.Supply(ManagedBy);
    CREATE INDEX IX_AuditLog_UserTime ON dbo.AuditLog(UserID, [TimeStamp]);
    CREATE INDEX IX_INCIDENTREPORT_HorseDate ON dbo.INCIDENTREPORT(HorseID, [Date]);
    CREATE INDEX IX_INCIDENTREPORT_Groom ON dbo.INCIDENTREPORT(GroomID);

    COMMIT TRANSACTION;
    PRINT N'Created 20 tables successfully.';
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;
GO
